### ISSUE TITLE
[BUG] Arms Reach Incompatibility

### ISSUE THREAD

**Issue by Q-efx** [MrVauxs/foundry-summons#1]
warpgate.js:69 Warp Gate | ERROR |  Events | error TypeError: Cannot read properties of undefined (reading 'id')
    at summon (summon.js:175:97)
    at async Events.run (warpgate.js:100:156)
    at async warpgate.js:193:184
    at async UpdateQueue.runUpdate (warpgate.js:187:142) 
 
In watch function (fs-summon)
 async ƒ summon(data) {
  if (!game.user.isGM)
    return ui.notifications.error(`Foundry Summons | ${localize("fs.notifications.error.permission")}`);
  debug("Received", data);
  if (game.settings.get(modul…

**Comment by MrVauxs** [comment]
On what system are you trying this on? 
Have you selected a creature to import before clicking Summon?

**Comment by Q-efx** [comment]
Foundry v11 302, newest module version. Yes selected. It creates a template or so, in pink, I guess thats where the creature should go, but nothing happens and i get this error.

**Comment by Q-efx** [comment]
Found the problem, its arms reach, for whatever reason, arms reach module gets in the way.

ArmsReachHelper.js:59 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 1 package: foundryvtt-arms-reach]
    at getMousePosition (ArmsReachHelper.js:59:136)
    at mn.<anonymous> (module.js:11:812)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)

You are forced to summon the creature in "door" range... Not sure, which module needs a fix then?

**Comment by MrVauxs** [comment]
Certainly something on Arms Reach, I am not doing anything but using `Warpgate`'s spawn function.

**Comment by MrVauxs** [comment]
> Found the problem, its arms reach, for whatever reason, arms reach module gets in the way.
> 
> ArmsReachHelper.js:59 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition') [Detected 1 package: foundryvtt-arms-reach] at getMousePosition (ArmsReachHelper.js:59:136) at mn. (module.js:11:812) at Na.notifyListeners (earcut.js:128:75) at Na.notifyTarget (earcut.js:128:75) at Na.propagate (earcut.js:128:75) at Na.dispatchEvent (earcut.js:128:75) at Na.mapPointerDown (earcut.js:128:75) at Na.mapEvent (earcut.js:128:75) at yn.onPointerDown (earcut.js:128:75)
> 
> You are forced to summon the creature in "door" range... Not sure, which module needs a fix then?

And it looks like this error also appears in general when using the module https://github.com/p4535992/foundryvtt-arms-reach/issues/76
