### ISSUE TITLE
Include the creature type for filtered list

### ISSUE THREAD

**Issue by ZeroXNoxus** [MrVauxs/foundry-summons#10]
It would be really nice if the creatures could be filtered via their creature type instead of just their name (DnD 5th Edition). It seems like this was already added for Path Finder 2nd Edition, so this could be a quick addition.

Maybe you also could add a filter field in the classic summoning menu with a drop-down of the existing creature types in the list.

**Comment by MrVauxs** [comment]
This is not implemented in PF2e, at least not by this module. 

You will want to add your own custom filter if you want to only see creatures of a specific type. There is no dropdown filter option yet, so feel free to make a request for those.
