### ISSUE TITLE
[BUG] "Sorted by" dropdown only contains "Alphabetical"

### ISSUE THREAD

**Issue by Suldrun45** [MrVauxs/foundry-summons#11]
**Module Version:** v1.5.0

**Describe the bug**
When I cast any summon spell, I don't get an option to sort the summons by level. I only get the option to sort them alphabetically

**To Reproduce**
1. Add a summon spell to a PF2e PC actor
2. Click on 'cast.'
3. Open the "Sorted by" dropdown

**Expected behavior**
The "Sorted by" dropdown should have options to sort by Level Ascending or Descending as it does when I use the Example Filtered Menu Macro or on the Open Summoning Menu Macro

**Screenshots**
![image](https://github.com/MrVauxs/foundry-summons/assets/49712710/193ab70d-9a96-4740-8f90-e837fb5d93f1)

**Browser:**
 - Chrome, Edge

**Foundry Version:** 
V11.306

**Game System:** 
PF2e system v5.2.3

**Comment by MrVauxs** [comment]
This is a PF2e Animations bug and will be fixed in the next update.
