### ISSUE TITLE
Pf1e summon list is empty.

### ISSUE THREAD

**Issue by Skeith86** [MrVauxs/foundry-summons#12]
Hello, I'm trying to run this module with Pf1e and after enabling all the Bestiaries in the settings, when I try to summon something by running the script I get an empty page like in this picture.
![image](https://github.com/MrVauxs/foundry-summons/assets/9444744/b7f107ad-c985-4c77-8780-066785281f0d)

**Comment by MrVauxs** [comment]
Do any of the creatures in the Bestiaries have images?

**Comment by Skeith86** [comment]
I don't know, but turning it off doesn't make any difference.

**Comment by MrVauxs** [comment]
Cannot replicate this in the newest version of Foundry Summons. Will close in a week if no further comments are made or if this has been fixed.

**Comment by Skeith86** [comment]
Is it possible that I've configured something incorrectly? What do I need to test.
I'm using Summons v 1.5.2 with Foundry 11 - Patch 8 (build 308)

**Comment by MrVauxs** [comment]
Go to settings, **Remove All**, and then **enable the compendiums you want**. Make sure to also **disable the Only Creatures with Images filter**.

Once they are enabled, open the Summon menu.

**Comment by Skeith86** [comment]
I'm afraid It didn't work.

**Comment by MrVauxs** [comment]
Can you send a screenshot of the Summon Menu with the Images filter disabled?

**Comment by Skeith86** [comment]
![image](https://github.com/MrVauxs/foundry-summons/assets/9444744/26c9539b-2adb-454c-a542-49cb5281fd65)

**Comment by MrVauxs** [comment]
You did not disable the Creatures with Images filter. Click on the filter on the left to disable it.
![image](https://github.com/MrVauxs/foundry-summons/assets/32039708/ccb8d2d1-4d14-4b86-9027-033116fe76e9)
