### ISSUE TITLE
Feature Request: Have Summoned Token Use Your Default Token Settings

### ISSUE THREAD

**Issue by GorgoPrimus** [MrVauxs/foundry-summons#15]
Right now if I have a character in pf2e summon a creature token, it’ll get summoned with settings such that it’s name and health never shown to anyone and it doesn’t get the dead condition on death. At the very least the first of these are settings the token spawns with that don’t match what I have set for new tokens I create myself when I drag a new actor into scenes and make it difficult for even the player controlling them to keep track of how they're doing.

It’d save people time and feel intuitive imo for summons from this to create tokens that follow your chosen ‘new token’ norms (but with allegiance set to the summoner's). But if that’s not how you want to handle things by default, could that at least be a setting toggle (“use token defaults” or something)?

Thanks for everything you’ve done either way!

**Comment by MrVauxs** [comment]
Please note that if you enabled the module **prior** to changing the default token settings, you have to enable Debug mode and delete the already created actors.

Then refresh. You will see the new actors with the used default token settings.
