### ISSUE TITLE
Token Disposition is not changed to match the Summoners.

### ISSUE THREAD

**Issue by rinnocenti** [MrVauxs/foundry-summons#18]
When conjuring the tokens, place them with the neutral/friendly disposition

**Comment by MrVauxs** [comment]
This is already the case. What version of Foundry Summons are you on?

![image](https://github.com/MrVauxs/foundry-summons/assets/32039708/706f52d4-bf81-47ad-b23d-dfa83746f96d)

**Comment by rinnocenti** [comment]
In Dnd5e not change.

**Comment by MrVauxs** [comment]
Was not aware this was a thing in 5e. Will investigate. Please state your system next time.
