### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YenBenGrey** [MrVauxs/foundry-summons#2]
**Module Version:** v1.1.0

**Describe the bug**
When opening the Open Summoning Menu the list of monsters is stuck in loading and the error attached happens

**To Reproduce**
1. Go to Open Summoning Menu
2. Click on Open Summoning Menu
3. Scroll down to N/A
4. See error - nothing loads

**Expected behavior**
A list of monsters should appear for me to chose to summon

**Screenshots**

**Browser:**
Chrome

**Foundry Version:** 
11.302
**Game System:** 
DND5e 2.2.1
**Additional context**
Warpgate is installed.
Chris Premades and all the dependencies
MidiQol, DAE.
<img width="1359" alt="Screenshot 2023-06-23 at 08 41 22" src="https://github.com/MrVauxs/foundry-summons/assets/98095856/30aa0739-51ed-489e-b3e5-79215bff4b27">

**Comment by MrVauxs** [comment]
Go to Module Settings and click "Return to Default" in Index Fields
![image](https://github.com/MrVauxs/foundry-summons/assets/32039708/bb45af3c-31f9-4bce-a939-acd75f5c1f8f)

See if that fixes your issue.

**Comment by YenBenGrey** [comment]
Hello there, that has worked thank you
