### ISSUE TITLE
D&D 5e request - pull from an approved 'list' for ranger or druid summons?

### ISSUE THREAD

**Issue by AkmenosDuFrey** [MrVauxs/foundry-summons#20]
LOVE this mod for my 5e game!! I was wondering if it would be too much of a problem to make the mod pull from a created list that the player has ownership of, like an 'approved' folder that has creatures it can summon for the summon woodland beings spell?
(I've no idea how it works but..) Kind of like having a folder the mod points to, that has creatures already pulled into it from the various manuals, and then that becomes the list they have available to summon from..
I hope I typed that correctly.

Thank you for the great work!!

**Comment by MrVauxs** [comment]
Would making a custom table with links to the creatures suffice?

Then you don't have to import every creature.

**Comment by AkmenosDuFrey** [comment]
That would be awesome! It would cover a lot of different uses as well
Thank you!

**Comment by MrVauxs** [comment]
The usage is as follows:
```js
const object = {
    creatures: "Summons", // This allows for the name of an Actor, the ID of an Actor, or an Array thereof, and the Folder name.
}

foundrySummons.openMenu(object)
```

**Comment by AkmenosDuFrey** [comment]
I'm sorry but I'm still learning - is this a macro subtext? 
If so, am I to change the "Summons" to the folder that her conjures are in?
Apologies

**Comment by MrVauxs** [comment]
Yes
