### ISSUE TITLE
[BUG] Warp Gate | ERROR | Events | Error

### ISSUE THREAD

**Issue by RinVindor** [MrVauxs/foundry-summons#21]
**Module Version:** v1.6.0

**Describe the bug**
I've setup the compendium to let players summon from and when I went to test the summoning. I am able to get the Pick a creature dialog box. I select one and have it summoned only to get a very generic `Warp Gate | ERROR | Events | Error` dialog at the top. And the summoning process simply halts at creating the Circle Template on the map. When I investigated in the console I get a good bit more going on but I'm not entirely able to decipher it. I haven't done anything with Warp Gate beyond have the module installed so its at default settings. With Foundry Summons I only set the Animal compendium and that was all.

Love the idea of this module and look forward to using it!

**Expected behavior**
A token should appear after being selected.

**Screenshots**
![image](https://github.com/MrVauxs/foundry-summons/assets/12647469/5c02c025-7b3b-4916-9c3f-ab27a3538efa)

**Browser:**
Opera GX

**Foundry Version:** 
V11.313

**Game System:** 
Chronicles of Darkness 2e V0.12.2

**Comment by MrVauxs** [comment]
What version of the module?

**Comment by MrVauxs** [comment]
Enable Debug mode and see if you have the following folder and actor 
![image](https://github.com/MrVauxs/foundry-summons/assets/32039708/f78e0de2-df41-4140-a4cb-11bf03faee59)

**Comment by RinVindor** [comment]
Enabled it and it seems I don't.

![image](https://github.com/MrVauxs/foundry-summons/assets/12647469/e0bc9c64-1138-4e43-aa04-06922c0e7dda)

**Comment by MrVauxs** [comment]
Check your console logs for errors when you load up the game. Every time you log in, it should check whether you have these blank actors and if you don't, generate them.

It is possible the module needs some system-specific fine-tuning for this one.

**Comment by MrVauxs** [comment]
I have installed the system and found the issue. Will rectify in a moment.

**Comment by MrVauxs** [comment]
I presume that any and all characters should be "character", not "ephemeral"?

**Comment by RinVindor** [comment]
Correct. Animals are under the Character section. Ephermal in this system can be summoned though 😅

**Comment by MrVauxs** [comment]
So preferably both should be usable?

**Comment by RinVindor** [comment]
Yeah that would be great!

**Comment by MrVauxs** [comment]
Fixed in 1.6.1
