### ISSUE TITLE
[BUG]Could not find the default blank NPC. 

### ISSUE THREAD

**Issue by Verata3** [MrVauxs/foundry-summons#23]
v1.6.2

Console Error during macro : Could not find the default blank NPC. Please refresh to generate one!

Enabled Debug Mode and found empty "foundry summons blank actors" folder, 
By reading your other issues i created a Blank NPC in this folder and refreshed by compendium macro .
Nothing changed. 
Another weird thing, the summoning menu from the macro i pasted below: left dropdown menu reveal only actor in the SCENE, right menu allows me to select the correct actors inside the selected compendium 
i made sure to have everything updated and it was.

![Screenshot 2023-12-12 231127](https://github.com/MrVauxs/foundry-summons/assets/153719939/cd05e3b8-3e05-4b85-a1d4-e342571a285e)
![Foundry Virtual Tabletop 12_12_2023 23_09_52](https://github.com/MrVauxs/foundry-summons/assets/153719939/254c7021-723a-4339-a828-e03e460588c9)

i am using this macro provided by Eskiemoh 

`let compendium = 'world.grimm-summons'
const object = {
    creatures: [game.packs.get (compendium)],
    options: {noAnimation: true}
}
let summon = await foundrySummons.openMenu(scope)

let summonToken = summon.tokenIds

for(i = 0; i < summon.amount; i++){
    
new Sequence()

.wait(50)

.effect()
.file('modules/jb2a_patreon/Library/Generic/Impact/Impact_11_Regular_Blue02_400x400.webm')
.atLocation(summonToken[i])
.scaleToObject(4)
.waitUntilFinished(-1000)

.animation()
.on(summonToken[i])
.opacity(1)

.play()

}`

thanks for your time

**Comment by MrVauxs** [comment]
"Refresh" means refreshing the webpage, or leaving the game and joining it back in case of you using the Foundry app.

Also you have entirely disregarded the template that gives me important information about the Foundry version, the system you are using, etc.

I have no idea what your other issue is. If you are talking about selecting who the Summoning Token is, yes, those include only the tokens on scene. And on the right theres anything you want because they are going to be summoned.

**Comment by Verata3** [comment]
Hi again
so i was refreshing correctly, then.
im using world building in the lastest update ( 0.8.5) 
the same for Foundry via software v11 build 315

the mods im using are:
Item Tag 1.1.0
advanced macros 2.0.5
compendium folders 2.6.1
daynight cycle 00007
dice so nice 4.6.8
effect macro 11.0.3
Forien's quest log 0.7.12
Foundry summoning 1.6.2
Freeform sheets 1.15.2
Fxmaster 4.0.2
image hover 3.0.3
improved macro editor10.1
item macro 1.10.3
Jack Kerouac's animated spell effects 0.4.5
JB2A 0.6.2
lib-color settings 3.0.1
libWrapper 1.12.13.0
Macro Grid 1.0.3
every Monk's modules 
 - tile triggers 11.17
 - Bloodsplats 11.11
 - Combat details 11.09
 - common display 11.05
 - enhanced journal 11.07
 - hotbar explansion 10.1
 - little details 11.05
 - player settings 11.04
 - Scene Navigation11.02
 - Sound enhancement 11.05
 - Tokenbar11.08
 - Wall enhancement 11.02
 Patrol 1.3.4
Potato or not 0.7.0
Sequencer 3.1.4
Simple calendar 2.4.3
Simple weather 1.8.0
Simple world building plus 1.1.0
Smalltime 1.19.1
Socketlib 1.0,13
Tagger 1.4.5
Times up 11.1.1
Tokenizer 4.2.8
WarpGate 1.19.2

Sorry for the lack of infos

what i was saying about left and right menu refers to this one, on the right i can see the macro is being read correctly ( it access the selected compendium) i dont know if its part of the issue but the left dropdown menu doesnt read the compendium, but every actor in the present scene. im just saying that cause maybe is an odd thing and can help with understanding better whats going on 

![Foundry Virtual Tabletop 13_12_2023 19_03_42](https://github.com/MrVauxs/foundry-summons/assets/153719939/83f938fe-348d-4ff3-8b9d-72502c4c2f58)

**Comment by MrVauxs** [comment]
Open the console when opening the world and look for any errors.

Foundry Summons **assumes** that the default type of NPC you want to summon is called "npc" in the data. If it anything different, you either need to rename it or need to wait until I support custom npc types being defined by the system, rather than the module.

https://github.com/MrVauxs/foundry-summons/blob/eb76fec5de4b53531514c057ec5030b0eff7c236/src/settings/templateActors/default.js#L31-L41

**Comment by Verata3** [comment]
> Open the console when opening the world and look for any errors.
> 
> Foundry Summons **assumes** that the default type of NPC you want to summon is called "npc" in the data. If it anything different, you either need to rename it or need to wait until I support custom npc types being defined by the system, rather than the module.
> 
> https://github.com/MrVauxs/foundry-summons/blob/eb76fec5de4b53531514c057ec5030b0eff7c236/src/settings/templateActors/default.js#L31-L41

Thats the issue! thanks a lot
console warning "error: undefined. SwpActor validation errors:
  type: npc is not a valid choice foundry.js:753

**Comment by MCH1984** [comment]
Hello,
I can repeat that error on a fresh test world without issues with only the following systems/modules and the macros that come with it:

Foundry 11 Build 315 (The latest stable one)
Shadowrun 5th Edition 0.17.1 (latest)
Foundry Summons 1.6.2 (latest)
Warp Gate 1.19.2 (latest)

I probably can't change the name without breaking the system. I wouldn't mind a workaround or something at some point, but it isn't overly important to me. Just thought some further info might help.

**Comment by MrVauxs** [comment]
It has been fixed in 1.7.0 @MCH1984 @Verata3

**Comment by MCH1984** [comment]
Tested it and works like a charm, thank you.
