### ISSUE TITLE
[BUG] Default NPC Not Generating

### ISSUE THREAD

**Issue by slave2midna** [MrVauxs/foundry-summons#24]
**Module Version:** v1.7.0

**Describe the bug**
When attempting to summon a creature, an error occurs that the blank NPC could not find the default blank NPC. Happens anytime I attempt to summon a creature.

**To Reproduce**
1. Launch Summoner Menu
2. Pick Creature
3. Click Summon
4. Attempt to Place Summon

**Expected behavior**
Should be able to summon a creature.

**Browser: Google Chrome, Edge**
 - 

**Foundry Version: v.11** 

**Game System: Custom Sheet System (CSB)** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by slave2midna** [comment]
I believe the issue may be the same as another issue - which is seems that NPCs in the system I use are referenced as type: 'character' and not type: 'npc' -- I do use Forge to run my foundry games, and I'm not sure it's possible to modify the default.js file to reflect this. Unless someone knows of a way to do so that I'm missing?

**Comment by MrVauxs** [comment]
Version 1.7.0 should generate all types of actors. Enable debug mode in module settings and check the Actors list for a Foundry Summons folder and if there is a `Dummy (character)` in it.

If there is not, open the console and look for any errors when refreshing the page. Foundry Summons should automatically attempt to create those dummy actors on load.

**Comment by slave2midna** [comment]
OH! That fixed it! Thank you! I guess I just wasn't refreshing it properly...Thank you so much!!
