### ISSUE TITLE
[BUG] An error message appears.

### ISSUE THREAD

**Issue by stevejew** [MrVauxs/foundry-summons#25]
**Module Version:** v1.7.0

**Describe the bug**
Ever since I deleted the compendium with containing summon actors, whenever I join the server, I get an error message.
On the client's side, an error message saying ""undefined" is not valid JSON [Detected 1 package: system:shadwroun5e]" appears.
On the player's side, there are a lot of messages that the player does not have the right to create or delete the actor.

**To Reproduce**
1. On the game settings menu, select the summoning source compendium.
2. delete the selected source compendium on compendium pack.
3. An error message appears when entering the server.

**Expected behavior**
The error message is not poping up.

**Screenshots**
client side error message
![image](https://github.com/MrVauxs/foundry-summons/assets/62639203/2fc25ccb-5d73-405d-a6e8-09c4a0baf797)
player side error message
![image](https://github.com/MrVauxs/foundry-summons/assets/62639203/e796b8ce-09f1-495e-867c-de275452ceff)

**Browser:**
 - Google Chrome, FVTT program

**Foundry Version:** 
v11 build 315
**Game System:** 
shadowrun 5e
**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by MrVauxs** [comment]
I have fixed the issue where the players get asked to create the empty NPC actors needed for the module to work.

As for the error, this looks like a system issue when attempting to fix empty inventories (?). Fixed it by not attempting to create the "base" actor type. Fixed in 1.7.1.
