### ISSUE TITLE
[BUG] Scrolling Status Text setting gets turned off when a creature is summoned

### ISSUE THREAD

**Issue by Deatrathias** [MrVauxs/foundry-summons#27]
**Module Version:** v1.7.2

**Describe the bug**
When a creature is summoned, the 'Scrolling Status Text' setting for the world gets disabled and isn't turned back on.

**To Reproduce**
1. Turn on 'Scrolling Status Text'
2. Summon a creature
3. Go into the settings menu again
4. Scrolling Status Text is turned off

**Expected behavior**
The setting remaining unchanged

**Foundry Version:** 
11 315

**Game System:** 
Pathfinder 2e 5.11.5

**Additional context**
The issue seems to be that the token flag that store the state of the 'Scrolling Status Text' value is lost when the token is turned into a object, and as a result, the setting isn't turned back on after the summoning.

**Comment by MightyMushka** [comment]
**Module Version:** v1.7.4

To add to this, I'm also able to reproduce with no other mods installed on the latest version.
