### ISSUE TITLE
[BUG] Unable to summon eidolon

### ISSUE THREAD

**Issue by Telain** [MrVauxs/foundry-summons#4]
**Module Version:** v1.4.0

**Describe the bug**
Uncaught (in promise) TypeError: undefined. $creature.serialize is not a function
[Detected 1 package: foundry-summons]
    at send (SummoningMenu.svelte:114:29)

**To Reproduce**
As user or GM, use "Manifest Eidolon"
Pick a creature pops up, minimized (if expanded, the eidolon is the only option)
Transparent eidolon image is on the cursor for placement, clicking results in error and a 2.5 ft circle template being placed. Eidolon is not summoned and pick a creature box remains open but minimized. Expanding it and clicking Summon 1 Name (Eidolon) repeats error.

**Expected behavior**
Eidolon is placed on map.

**Browser:**
Chrome 114.0.5735.134 (64-bit)

**Foundry Version:** 11.302

**Game System:** Pathfinder 2nd Edition 5.0.2

**Additional context**
Add any other context (like other modules installed) about the problem here.
Modules:
Automated Animations 4.2.60
PF2e Animations 2.15.2
Sequencer 3.0.14
socketlib 1.0.13
Warp Gate 1.17.2

**Comment by MrVauxs** [comment]
[Fixed in PF2e Animations.](https://github.com/MrVauxs/pf2e-jb2a-macros/commit/3670b512439335125b032199a1baaa805c30c9e0)
