### ISSUE TITLE
[BUG] No image summon

### ISSUE THREAD

**Issue by Telain** [MrVauxs/foundry-summons#5]
**Module Version:** v1.4.0

**Describe the bug**
Uncaught (in promise) Error: Sequencer | Module: Automated Animations | Effect | size - inSize must be of type number or object
    at custom_error (lib.js:451:10)
    at Proxy._customError (sequencer.js:402:12)
    at Proxy.size (effect.js:1012:27)
    at sourceEffect (commonSequences.js:15:6)
    at AAHandler.compileSourceEffect (workflow-data.js:226:9)
    at Module.ontoken$3 [as ontoken] (staticAnimation.js:29:17)

**To Reproduce**
As user, cast "Dancing Lights"
Pick a creature pops up, select any color
Proper transparent image pops up and it summons the tokens, but they have no image and throws the error.

**Expected behavior**
Dancing lights have token images.

**Browser:**
Chrome 114.0.5735.134 (64-bit)

**Foundry Version:** 11.302

**Game System:** Pathfinder 2nd Edition 5.0.2

**Additional context**
Works when cast as GM. User is "Trusted Player" with permission to everything except "Modify Configuration Settings"
Attempted with "Summon Animal" to summon 1 eagle. Same effect.
Opening the token config, I found it actually has an image applied, but it's not visible on the map. Refreshing doesn't change this.

Modules:
Automated Animations 4.2.60
PF2e Animations 2.15.2
Sequencer 3.0.14
socketlib 1.0.13
Warp Gate 1.17.2

I had reenabled my other modules before taking this picture of the eagle attempt, but the result was the same.

![image](https://github.com/MrVauxs/foundry-summons/assets/1679073/26b65690-9101-4d33-a561-8ca93b03a8ed)

**Comment by MrVauxs** [comment]
Fixed in [PF2e Animations](https://github.com/MrVauxs/pf2e-jb2a-macros/commit/6e772894530e2da12680dbf6b3bdc40fa8f7a521).
