### ISSUE TITLE
Summon should include Create Undead

### ISSUE THREAD

**Issue by AKA-Kira** [MrVauxs/foundry-summons#7]
I may just be implementing it incorrectly to tie it to the Pathfinder 2E Spell Create Undead, as I have a necromancer in one of my groups and this implementation would make using these types of spells a lot more streamlined.

**Comment by MrVauxs** [comment]
PF2e Animations includes a macro and animation for Create Undead. 

You can easily make a macro yourself as well by looking at the example macro in Foundry Summons compendium and changing the filter function.

**Comment by AKA-Kira** [comment]
I will try to make the Macro myself, just odd that I am not getting the summon options using Create Undead

**Comment by AKA-Kira** [comment]
I did figure out how to configure the trait filter since only one creature has Undead in the name, which is a good work around for now, interesting the Create Undead PF2E Animations macro is not working for Create Undead

**Comment by MrVauxs** [comment]
I just realized that you were talking about the ritual "Create Dead", not the spell "Animate Dead".

Yes, Create Dead has not been automated in PF2e Animations. You can just copy over the Animate Dead settings in Automated Animations.
